// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe1Gj_RaiPtC2fcdcI3-P7v0EnGAWykuk',
    appId: '1:73510414994:web:5ef7554a68c62b18ce544b',
    messagingSenderId: '73510414994',
    projectId: 'elite-hotel-26752',
    authDomain: 'elite-hotel-26752.firebaseapp.com',
    storageBucket: 'elite-hotel-26752.appspot.com',
    measurementId: 'G-EBRTERMSCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF0xU0m5jntIoxwE2EVucl9zxSWbh1u0I',
    appId: '1:73510414994:android:51e4390b93549987ce544b',
    messagingSenderId: '73510414994',
    projectId: 'elite-hotel-26752',
    storageBucket: 'elite-hotel-26752.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Ps2oPtB-Jue4atd5Tmr1SG4e6x0bx-o',
    appId: '1:73510414994:ios:1afe16706b66405dce544b',
    messagingSenderId: '73510414994',
    projectId: 'elite-hotel-26752',
    storageBucket: 'elite-hotel-26752.appspot.com',
    iosBundleId: 'com.example.elitehotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Ps2oPtB-Jue4atd5Tmr1SG4e6x0bx-o',
    appId: '1:73510414994:ios:1afe16706b66405dce544b',
    messagingSenderId: '73510414994',
    projectId: 'elite-hotel-26752',
    storageBucket: 'elite-hotel-26752.appspot.com',
    iosBundleId: 'com.example.elitehotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe1Gj_RaiPtC2fcdcI3-P7v0EnGAWykuk',
    appId: '1:73510414994:web:e1ba59595f23d713ce544b',
    messagingSenderId: '73510414994',
    projectId: 'elite-hotel-26752',
    authDomain: 'elite-hotel-26752.firebaseapp.com',
    storageBucket: 'elite-hotel-26752.appspot.com',
    measurementId: 'G-VT4RL1TC1F',
  );
}
